name: FlutterGalleryApp
description: Amazing Flutter Project
author: ruslanjava

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  webview_flutter: ^0.3.22+1
  dio: ^3.0.9
  cached_network_image: 2.2.0+1
  cupertino_icons: ^0.1.3
  json_annotation: ^3.0.1
  connectivity: ^0.4.9+2
  gallery_saver: 2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.3.0

flutter:
  uses-material-design: true
  fonts:
      - family:  AppIcons
        fonts:
         - asset: assets/fonts/AppIcons.ttf
